<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCoreRateLimit" />
    <PackageReference Include="FluentValidation.AspNetCore" />
    <PackageReference Include="HtmlSanitizer" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="QRCoder" />
    <PackageReference Include="reCAPTCHA.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Sentry.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OazaDlaAutyzmu.Application\OazaDlaAutyzmu.Application.csproj" />
    <ProjectReference Include="..\OazaDlaAutyzmu.Infrastructure\OazaDlaAutyzmu.Infrastructure.csproj" />
  </ItemGroup>

</Project>
