<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OazaDlaAutyzmu.Application\OazaDlaAutyzmu.Application.csproj" />
    <ProjectReference Include="..\..\src\OazaDlaAutyzmu.Domain\OazaDlaAutyzmu.Domain.csproj" />
    <ProjectReference Include="..\..\src\OazaDlaAutyzmu.Infrastructure\OazaDlaAutyzmu.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\OazaDlaAutyzmu.Web\OazaDlaAutyzmu.Web.csproj" />
  </ItemGroup>

</Project>